export const PRODUCT_CATEGORIES = [
    { id: "commodes", name: "Комоди" },
    { id: "wardrobes", name: "Шафи розпашні" },
    { id: "pencil_cases", name: "Пенали" },
    { id: "bedside_tables", name: "Тумби приліжкові" },
    { id: "computer_desks", name: "Столи комп'ютерні" },
    { id: "wall_hangers", name: "Вішалки настінні" },
    { id: "floor_hangers", name: "Вішалки напольні" },
    { id: "shoe_cabinets", name: "Тумби під взуття" },
    { id: "tv_stands", name: "Тумби під ТВ" },
    { id: "wall_units", name: "Стінки" },
    { id: "coffee_tables", name: "Столи журнальні" },
    { id: "shelves", name: "Полиці" },
    { id: "single_beds", name: "Ліжка односпальні" },
    { id: "double_beds", name: "Ліжка двоспальні" },
    { id: "mirrors", name: "Дзеркала" },
    { id: "chairs", name: "Крісла" },
    { id: "tables", name: "Столи" },
    { id: "sofas", name: "Дивани" },
    { id: "lamps", name: "Лампи" },
    { id: "decor", name: "Декор" },
];
